<script>
		function testes(){
			return new Promise((resolve,rejetcted)=>{
				const erro = true


				if(erro){
					rejetcted('Error')
				}else{

					resolve('Resolvido com sucesso!!!')
				}
			})
		}
		testes().then((res)=>{
			alert(res)
		}).catch(function(e){
			alert(e)
		})

	</script>
